### ISSUE TITLE
您好，能提供一下预训练模型吗？

### ISSUE THREAD

**Issue by Dysonsun** [TomMao23/multiyolov5#1]

**Comment by TomMao23** [comment]
预训练模型过几天会和 tag TomMao-2.0 一起发出来。2.0出来前最好别用主分支，如果现在训练可以用1.8，用yolov5官方COCO检测预训练模型初始化分割收敛很快，20轮就已经很好了

**Comment by TomMao23** [comment]
> ## grey_questionQuestion
> ## Additional context

2.0和预训练模型已发布

**Comment by TomMao23** [comment]
> ## grey_questionQuestion
> ## Additional context

2.0和预训练模型已发布

**Comment by TomMao23** [comment]
pretrained models has been released
