### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR有遇到的嘛？

### ISSUE THREAD

**Issue by luna9806** [TomMao23/multiyolov5#11]
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([8, 128, 52, 104], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(128, 2, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_HALF
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 000001F1E879F590
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 8, 128, 52, 104,
    strideA = 692224, 5408, 104, 1,
output: TensorDescriptor 000001F1E879F670
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 8, 2, 52, 104,
    strideA = 10816, 5408, 104, 1,
weight: FilterDescriptor 000001F1A0BDA0D0
    type = CUDNN_DATA_HALF
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 2, 128, 1, 1,
Pointer addresses:
    input: 000000078F464000
    output: 0000000765FC1E00
    weight: 0000000765DFFE00

**Comment by lindiedie** [comment]
I got same question, did you solve it? I change batch_size=1, but it's still not work. @luna9806 @topiaruss @jakepoz @olehb @pcgeek86
