### ISSUE TITLE
关于pt转onnx问题

### ISSUE THREAD

**Issue by Salary-only-17k** [TomMao23/multiyolov5#18]
## ❔Question
用model下面的export，seg头结果不一致。
## Additional context
使用的是yolov5m_citybdd.yaml 配置文件

**Comment by Salary-only-17k** [comment]
有人试着转过吗？请多指教

**Comment by Salary-only-17k** [comment]
转模型不行呀。通过onnx转的，网络结构都变了。

**Comment by yangdi-cv** [comment]
请问这个解决了吗

**Comment by lucameng** [comment]
同问
