### ISSUE TITLE
python convert2Yolo/example.py 

### ISSUE THREAD

**Issue by Ocean-ZHY** [TomMao23/multiyolov5#3]
## Additional context
你好 在处理数据的时候并没有在convert2Yolo的文件夹下找到example.py 文件

**Comment by TomMao23** [comment]
> ## ❔Question
> ## Additional context
> 你好 在处理数据的时候并没有在convert2Yolo的文件夹下找到example.py 文件
convert2Yolo是ssaru的github仓库，如果发现这里不能使用，请在本仓库convert2Yolo所在文件夹下删除convert2Yolo后
git clone https://github.com/ssaru/convert2Yolo

**Comment by Ocean-ZHY** [comment]
好的  感谢您的解答

**Comment by TomMao23** [comment]
主分支已修复
