### ISSUE TITLE
‍致近期使用multiyolov5仓库的各位

### ISSUE THREAD

**Issue by TomMao23** [TomMao23/multiyolov5#4]
明天开始我将专心投入到考研中，仓库近期不会再有结构/功能上的更新。   
若后续考上研我会继续在本仓库    
1. 跟进yolov5的后续更新（P6看上去挺适合做分割的）
2. 尝试新的分割头
3. 增加更多任务的集成比如MOT和depth estimation等
4. 重构接口（毕设赶时间接口确实很烂，代码也东拼西凑魔改比较乱）
5. 增加多卡训练和部署的支持。

近期遇到较为明显的bug麻烦请在issue中指出，我会尽力在空闲时间修复。但训custom data之类的问题我近期将不再回复。训练自己的数据是一个比较专门的问题，各个数据集有适合的方案(包括结构和数据增强)，一些通用的数据增强手段可能并不是适合你的数据(例如在红绿灯左右箭头识别中使用随机水平翻转，yolov5的mosaic增强对某些数据不合适)，因此若训练自己的模型最好熟悉原版yolov5和本仓库的代码。

**Comment by BowieHsu** [comment]
感谢开源，学习一波

**Comment by guoguoguo123** [comment]
感谢开源，祝考研顺利

**Comment by jie311** [comment]
祝大神考研顺利
