### ISSUE TITLE
IndexError: index 483 is out of bounds for axis 0 with size 19

### ISSUE THREAD

**Issue by WhXl** [TomMao23/multiyolov5#5]
感谢你开源了你的项目，我运行代码遇到了这个问题！

## 🐛 Bug
File "/home/wx/Projects/multiyolov5/detect.py", line 197, in detect
    mask = label2image(seg.max(axis=0)[1].cpu().numpy(), Cityscapes_COLORMAP)[:, :, ::-1]
  File "/home/wx/Projects/multiyolov5/detect.py", line 72, in label2image
    return colormap[X, :]
IndexError: index 483 is out of bounds for axis 0 with size 19

## To Reproduce (REQUIRED)

Input:
```
def label2image(pred, COLORMAP=Cityscapes_COLORMAP):
    colormap = np.array(COLORMAP, dtype='uint8')
    X = pred.astype('int32')
    return colormap[X, :]
```

Output:
```
Traceback (most recent call last):
  File "/home/wx/Projects/multiyolov5/detect.py", line 279, in <module>
    detect()
  File "/home/wx/Projects/multiyolov5/detect.py", line 197, in detect
    mask = label2image(seg.max(axis=0)[1].cpu().numpy(), Cityscapes_COLORMAP)[:, :, ::-1]
  File "/home/wx/Projects/multiyolov5/detect.py", line 72, in label2image
    return colormap[X, :]
IndexError: index 483 is out of bounds for axis 0 with size 19
```

## Environment

 - OS: ubuntu16.04
 - GPU [e.g. 2070] torch 1.7.1+cu101 CUDA:0 (GeForce RTX 2070, 7979.1875MB)

**Comment by Zomcxj** [comment]
同 还没开始就结束了！

**Comment by Zomcxj** [comment]
> 同 还没开始就结束了！

应该是v5的权重不行  要下载作者百度云新的权重才可以

**Comment by TomMao23** [comment]
Do not use yolov5s.pt and yolov5m.pt when inference, use other weight in baiduyun.

**Comment by TomMao23** [comment]
> > 同 还没开始就结束了！
> 
> 应该是v5的权重不行 要下载作者百度云新的权重才可以



> > 同 还没开始就结束了！
> 
> 应该是v5的权重不行 要下载作者百度云新的权重才可以

原版的yolov5s.pt和yolov5m.pt我保留在了网盘中，但不可用于推理，仅用作训练时候初始化来迁移学习。推理时使用百度网盘里其他几个预训练权重。

**Comment by WhXl** [comment]
谢谢，这个换做百度网盘中权重后，问题得到了解决

**Comment by SYL888** [comment]
谢谢，解决了
